services:
  database:
    image: madddsnail/car-rental-database:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker

  backend:
    image: madddsnail/car-rental-backend:latest
    depends_on:
      - database
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.role == backend
      restart_policy:
        condition: on-failure

  frontend:
    image: madddsnail/car-rental-frontend:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.role == frontend
      restart_policy:
        condition: on-failure

  reverse-proxy:
    image: madddsnail/car-rental-reverse-proxy:latest
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

volumes:
  db_data:
