name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car-rental-backend:latest ./Backend
        docker push ${{ secrets.DOCKER_USERNAME }}/car-rental-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car-rental-frontend:latest ./Frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/car-rental-frontend:latest

    - name: Build and push reverse-proxy image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car-rental-reverse-proxy:latest ./ReverseProxy
        docker push ${{ secrets.DOCKER_USERNAME }}/car-rental-reverse-proxy:latest

    - name: Build and push database image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car-rental-database:latest ./Database
        docker push ${{ secrets.DOCKER_USERNAME }}/car-rental-database:latest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SWARM_MANAGER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Docker Swarm
      run: |
        scp docker-stack.yml root@${{ secrets.SWARM_MANAGER_IP }}:${{ secrets.WORKING_DIRECTORY }}/docker-stack.yml
        ssh root@${{ secrets.SWARM_MANAGER_IP }} "docker stack deploy -c ${{ secrets.WORKING_DIRECTORY }}/docker-stack.yml car-rental"
